Calculate and chart total population data from input
MastodonC/witan.send.vis pull request #28
Opened 2021-09-28 16:02 UTC by seb231

2021-09-28 16:24 UTC, seb231 commented on src/witan/send/vis/general_population.clj
> +   ["Total General Population" #{99}]])
a string here doesn't work

2021-09-28 21:27 UTC, otfrom approved these changes
Magic 99 makes me really, really itchy.

2021-09-29 09:42 UTC, seb231 commented
Agreed to leave comments everywhere "99" exists

2021-09-29 12:27 UTC, otfrom requested changes
add `FIXME: ` at the front as I search for that and some modes highlight that for you automagically

2021-09-29 12:27 UTC, otfrom commented on src/witan/send/vis/general_population.clj
> +                         ;; 99 is used as a placeholder where data structures require a number be present but is
add `FIXME: ` at the front as I search for that and some modes highlight that for you automagically

2021-09-29 12:27 UTC, otfrom commented on src/witan/send/vis/general_population.clj
> +   ;; 99 is used as a placeholder where data structures require a number be present but is
add `FIXME: ` at the front as I search for that and some modes highlight that for you automagically

2021-09-29 12:30 UTC, otfrom approved these changes

2021-09-29 12:35 UTC, merged